package com.studyspace.models;

public enum ActivityType {
    QUIZ_COMPLETED,
    FLASHCARDS_REVIEWED,
    NOTES_ADDED,
    CODE_PROBLEM_SOLVED,
    STUDY_SESSION_STARTED,
    STUDY_SESSION_ENDED,
    TODO_ITEM_ADDED,
    TODO_ITEM_COMPLETED,
    FLASHCARD_DECK_CREATED,
    QUIZ_TAKEN,
    NOTE_EDITED,
    CODE_PROBLEM_ATTEMPTED
}

